function [numf,nomf,apef]=ocrCedulaFrontal(img)
    edgeThreshold = 1;
    amount = 0.4;
    img = localcontrast(img, edgeThreshold, amount);
    a4= components(img);
    a4=component(a4,1);
    a4=imadjust(a4);
    a4(a4>190)=255;
    a4(a4<191)=0;
    s1 = strel('square',1);%aplica elemento estrucurante en un diamante
    se = strel('line', 1, 90);
    a4=imerode(a4,se);% se quit el ruido de la imagen
    a4=imerode(a4,s1);
    a4=bwareaopen(a4,40);
    b=a4';
    c=sum(b);
    c1=find(c>80);
    [tamx,tamy]=size(c1);
    inicio=c1(1);
    fin=c1(tamy);
    numero=b(:,inicio-2:inicio+22);
    apellidos=b(:,inicio+22:inicio+50);
    nombres=b(:,fin-20:fin+2);
    %%%-------- Se ponen las imagenes en sentido horizontal --------------%%%%
    numero=numero';
    nombres=nombres';
    apellidos=apellidos';
    se = strel('disk',1);
    numero=imerode(numero,se);
    nombres=imerode(nombres,se);
    apellidos=imerode(apellidos,se);
    numf=ocr(numero);
    numf= numf.Text;
    numf= obtenerNumeros(numf);
    nomf=ocr(nombres);
    nomf= nomf.Text;
    nomf= obtenerLetras(nomf);
    apef=ocr(apellidos);
    apef= apef.Text;
    apef= obtenerLetras(apef);
end 
